name: quality-ci
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: sonar

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: install dependencies
        run: npm install

      - name: run build script
        run: npm run coverage

      - name: get current package version
        id: get_version
        run: echo ::set-output name=PACKAGE_VERSION::$(node -e "console.log(require('./package.json').version);")

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectVersion=${{ steps.get_version.outputs.PACKAGE_VERSION }}

